config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"

  root to: "home#index"
  get "/users", to: "home#index"
  get "/certificate", to: "home#show_certificate"
  devise_for :users
  resource :student, controller: "student"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :student
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :user
  has_one :parent, dependent: :delete
  accepts_nested_attributes_for :parent, allow_destroy: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :student, dependent: :destroy
  has_one :parent, through: :student, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  private

  def after_sign_out_path_for(resource_or_scope)
    if resource_or_scope == :user
      return root_path
    end
    # if current_user
    #   request.referrer
    # else
    #   root_path
    # end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, :only => :index

  def show_certificate
    send_data CreatePdfJob.set(wait: 10.seconds).perform_now(current_user), filename: "Certificate.pdf", disposition: "attachment"
  end

  def index
  end
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
  def new
    @student = Student.new
    @parent = Parent.new
    @url = student_path
    render "form"
  end

  def edit
    @student = current_user.student
    @parent = @student.parent
    @url = student_path
    render "form"
  end

  def create
    @student = current_user.build_student(student_params)
    @parent = current_user.student.build_parent(parent_params)
    if @student.save && @parent.save
      send_data CreatePdfJob.set(wait: 10.seconds).perform_now(current_user), filename: "Certificate.pdf", disposition: "attachment"
      # redirect_to "/"
    else
      flash[:alert] = @student.errors.full_messages.join(", ")
      flash[:alert] += @parent.errors.full_messages.join(", ")
      redirect_to "/"
    end
  end

  def update
    @student = current_user.student
    @parent = current_user.student.parent
    @student.update(student_params)
    @parent.update(parent_params)

    if @student.save && @parent.save
      send_data CreatePdfJob.set(wait: 10.seconds).perform_now(current_user), type: "pdf", filename: "Certificate.pdf", disposition: "attachment"
      # redirect_to "/"
    else
      flash[:alert] = @student.errors.full_messages.join(", ")
      flash[:alert] += @parent.errors.full_messages.join(", ")
      redirect_to "/"
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :standard, :date_of_birth, :section, :admission_number)
  end

  def parent_params
    params.require(:student).require(:parent).permit(:father_name, :mother_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container" style="margin: 0 10%;">
    <% # <a class="navbar-brand" href="#">School Mitra</a> %>
    <%= link_to "School Mitra", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <% if current_user %>
        <% if current_user.student %>
        <li class="nav-item">
        <%= link_to "Student Info", edit_student_path, class: "nav-link active" %>
        </li>
        <% end %>
        <% end %>
        <li class="nav-item">
          <% # <a class="nav-link" href="#">Pricing</a> %>
        </li>
      </ul>

        <section class="d-flex">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">   
            <% if !user_signed_in? %>
            <li class="nav-item">
              <% # <a class="nav-link active" aria-current="page" href="#" >Sign in</a> %>
              <%= link_to "Sign in", new_user_session_path, class: "nav-link active" %>  
            </li>
            <% end %>
            <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Edit login info", edit_user_registration_path, class: "nav-link active" %>  
            </li>
            <li class="nav-item">
              <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "btn btn-primary" %>  
            </li>
            <% end %>
                      <% # <span class="navbar-text"> Navbar text with an inline element </span> %>
          </ul>
        </section>

    </div>
  </div>
</nav>

app/views/home/certificate.html.erb
<!doctype html>
<html>
  <head>
    <meta charset='utf-8' />

        <%= stylesheet_link_tag wicked_pdf_asset_base64("certificate") %>

  </head>
  <body onload='number_pages'>
    <div id="header">
      <% # <%= wicked_pdf_image_tag "runner.jpg" %> 

    <% # <div class="top"> %>
      <%= image_tag wicked_pdf_asset_base64("ace.png"), class: "logo" %>
      <section class="main-content">
      <h1 class="heading">Demo School</h1>
        Varanasi, Uttar Pradesh<br/>Reg No. 376357<br/>
        English Medium School<br/>

        <p class="title">CHARACTER CERTIFICATE</p>
        <p class="subtitle">TO WHOM IT MAY CONCERN</p>

        <p class="content">
        This is to certify that Miss/Master <%= current_user.student.name %> S/D of Mr. <%= current_user.student.parent.father_name %> is/was a bonafide student of our
        school.<br/> As per our school record his/her Date of Birth is <%= current_user.student.date_of_birth.strftime("%d-%B-%Y") %>.<br/>
        He/She possesses a good moral conduct and behaviour.<br/>
        We wish him/her a bright future.<br/>
        </p>

        <div class="footing" >
        <p class="designation">Principal</p>
        <p class="date">Date: <%= Date.today.strftime("%A, %d-%B-%Y") %></p>
        </div>


     </section>
    </div>

    <div id="content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/home/index.html.erb
<div class="container" >
<h1 class="mt-4" style="text-align:center">Welcome to SchoolMitra</h1>

<% if user_signed_in? %>
   <div style="text-align:center">
      <% if current_user.student %>
         <%= link_to "View Certificate", certificate_path(format: :pdf), method: :get, class: "mt-5 btn btn-lg mx-auto btn-primary", style: "color#fff;" %>

      <% else %>
         <%= link_to "Get my Certificate", new_student_path, method: :get, class: "mt-5 btn btn-lg mx-auto btn-primary", style: "color#fff;" %>

      <% end %>
   </div>

<% else %>
   <div style="text-align:center; ">
   <p class="subtitle mt-3" style="text-decoration:none;">Create Your free account today!<br/>
   <%= link_to "Sign up", new_user_registration_path, class: "mt-4 btn btn-lg btn-primary" %>

<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School Mitra</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>

  </head>

  <body>
    <%= render partial: "home/nav" %>

    <% if flash[:notice] %>
      <div class="container mt-2 alert alert-primary alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="container mt-2 alert alert-warning alert-dismissible fade show" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>
    <div class="container">
    <%= yield %>
    </div>
  </body>
  

  </html>

app/views/student/create_form.html.erb
<main class="container mx-auto border m-3" style="max-width:500px;">

<h4 style="text-align:center;" class="border-bottom p-2">
Fill the details correctly to Generate Certificate!</h4>

<section >

<%= form_with url: student_create_path do |form| %>


    <div class="form-group">  
        <p class="form-label">Name <span>*</span> </p>
        <%= form.text_field :name, required: "required", class: "mb-2 form-control" %>
    </div>
    <div class="form-group">  
        <p class="form-label">Father Name <span>*</span> </p>
        <%= form.text_field :father_name, required: "required", class: "mb-2 form-control" %>
    </div>    <div class="form-group">  
        <p class="form-label">Mother Name <span>*</span> </p>
        <%= form.text_field :mother_name, required: "required", class: "mb-2 form-control" %>
    </div>   
    <div class="form-group">  
        <p class="form-label">Standard <span>*</span> </p>
        <%= form.text_field :standard, required: "required", class: "mb-2 form-control" %>
    </div>
    <div class="form-group">  
        <p class="form-label">Section <span>*</span> </p>
        <%= form.text_field :section, required: "required", class: "mb-2 form-control" %>
    </div>
    <div class="form-group">  
        <p class="form-label">Date Of Birth <span>*</span> </p>
        <%= form.date_field :date_of_birth, required: "required", class: "mb-2 form-control" %>
    </div>    
    <div class="form-group">  
        <p class="form-label">Admission Number <span>*</span> </p>
        <%= form.text_field :admission_number, required: "required", class: "mb-2 form-control" %>
    </div>
    <div class="form-group">
        <%= form.submit "Generate Certificate", class: "mb-2 form-control btn btn-primary" %>
    </div>
<% end %>

</section>

</main>

app/views/student/form.html.erb
<main class="container mx-auto border m-3" style="max-width:500px;">

<h4 style="text-align:center;" class="border-bottom p-2">
Fill the details correctly to Generate Certificate!</h4>

<section >
 
<%= form_with(model: @student, url: @url) do |form| %>

    <div class="form-group">  
        <p class="form-label">Name <span>*</span> </p>
        <%= form.text_field :name, class: "mb-2 form-control" %>
    </div>

        <%= form.fields_for(@parent) do |f| %>
    <div class="form-group">  
        <p class="form-label">Father Name <span>*</span> </p>
        <%= f.text_field :father_name, class: "mb-2 form-control" %>
    </div>    
    <div class="form-group">  
        <p class="form-label">Mother Name <span>*</span> </p>
        <%= f.text_field :mother_name, class: "mb-2 form-control" %>
    </div>   
    <% end %>
    <div class="form-group">  
        <p class="form-label">Standard <span>*</span> </p>
        <%= form.text_field :standard, class: "mb-2 form-control" %>
    </div>
    <div class="form-group">  
        <p class="form-label">Section <span>*</span> </p>
        <%= form.text_field :section, class: "mb-2 form-control" %>
    </div>
    <div class="form-group">  
        <p class="form-label">Date Of Birth <span>*</span> </p>
        <%= form.date_field :date_of_birth, required: "required", class: "mb-2 form-control" %>
    </div>    
    <div class="form-group">  
        <p class="form-label">Admission Number <span>*</span> </p>
        <%= form.text_field :admission_number, class: "mb-2 form-control" %>
    </div>
    <div class="form-group">
        <%= form.submit class: "mb-2 form-control btn btn-primary" %>
    </div>
<% end %>

</section>


</main>